const Art = require("./art.js");

const Endings = [
    ['After working even longer on the project, you can feel your head spin around.', 'Becoming THAT fatigued is not good for you!', 'You just keep on working, although taking a breath is more difficult by the second.', 'Taking breaths is almost impossible now!', 'You feel everything fade slowly, slowly to black...', 'Ending 0: Died by fatigue from working on your text adventure.'],
    ['Carlos Emanuel Juan Stephagonos sighs out of relief \"I got a medicine for you!\"', 'He gives you the medicine and it works! No more illness!', 'You go back home and watch some Netflix, proud of the work you have done', 'Ending 1: Cured by Carlos Emanuel Juan Stephagonos'],
    ['As you float around in the void, you begin feeling colder.', 'You look at your hand, getting pale from the cold.', 'As you slowly lose the ability to move, the only thing left to do is float in the void.', 'Ending 2: Frozen to death in the void.'],
    ['You sigh in relief knowing that, even though this body may not be truly yours, you didn\'t die too!', 'Ending 3: Solved merge conflict with your younger self (programming pun intended)'],
    ['As you run to touch the orb before the younger you can, time slowly begins warping all around you.', 'The second your finger touched that orb, you get violently ripped apart and die.', 'You created something that should not be possible, because you touched the orb, but you would not be there if the younger you didn\'t touch it.', 'Ending 4: Ripped to death by extraterrestrial force.'],
    ['You don\'t rush to touch the orb but patiently wait, you can see your younger self touch the orb and become you, but in the act of not touching the orb, a time loop was created, only you remember every. Single. One of them.', 'For millions of years you will forget to remember anything but that time loop making you go insane.', 'Over the centuries, you slowly become braindead and ended the time loop, but the only thing you can do is lay on the floor, not knowing who you are, what you are, nor where you are..', 'Ending 5: Insanity by a time loop'],
    ['You tell the police you want to play peek-a-boo with the orb.', 'The police laugh at you and say \"Ok smartass, if you want to play some children\'s game with an inanimate object, go ahead\"', 'As you open your palms, the orb is gone. The police are baffled beyond belief!', 'One officer says \"IT JUST VANISHED?!\"', 'You, obviously smugging, tell the officers the orb got scared and fled.', 'Ending 6: Shocked the police by playing peek-a-boo with an inanimate object.'],
    ['As you inch closer to the orb, your brain gets overloaded with information.', 'Your ears are bleeding from the screaming and you became basically blind', 'As you begin to lose touch with reality you collapse to the ground into the orb.', 'You were destroyed in the process.', 'Ending 7: Made insane and died by the orb'],
    ['As you are rewiring the time machine, the LEDs go off, the right time coordinates were there all along!', 'Then you hear a spark, the wires you were changing up REALLY messed up the time machine now!', 'Then you start to smell something, smoke?', 'Before you could even realise what\'s going on, the time machine explodes and you die in the void.', 'No one will notice you are gone, forever lost in time.', 'Ending 8: Exploded together with the time machine'],
    ['Of course! The classic :D', 'As you give it a good ol\' smack, you hear some metal sounds...', 'The air conditioning has a loose screw!', 'The vent pops out, and as you want to put it back, it explodes.', 'And not just the vent, the whole time machine explodes. You die in the explosion, and the orb will never be found again.', 'Ending 9: Just like the dinosaurs!'],
    ['The feral alien sees you doing... nothing.', 'It look at you weirdly, the feral alien expected you to be scared, but instead he throws you out in the void, out the broken window.', 'Thinking about it, it wasn\'t worth the 10 euro. So you slowly freeze to death in the void', 'Ending 10: Frozen to death in the void, just like my will to live!']
];

module.exports = Endings;